import "./globals.css";
import type { Metadata } from "next";
import { Inter, Encode_Sans } from "next/font/google";
import { ThemeProvider } from "@/providers/themeProvider";
import NavBar from "./components/NavBar";
// import { motion, useScroll } from "framer-motion";
import SideScroll from "./components/SideScroll";
import { Toaster } from "@/components/ui/toaster";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });
const encodeSans = Encode_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Brandon Dykun",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark w-[100vw] scroll-smooth">
      <body
        className={`${encodeSans.className} flex min-h-screen w-[100vw] relative`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="w-12 sm:flex flex-col h-screen bg-stone-300 dark:bg-stone-950 top-0 bottom-0 left-0 justify-center items-center fixed hidden">
            <div className="absolute top-4 left-3 text-accent font-bold">
              BD
            </div>
            <SideScroll />
          </div>
          <div className="flex flex-col flex-1 sm:pl-12">
            <NavBar />
            {children}
            <Footer />
          </div>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
